language: c
sudo: required
dist: bionic

matrix:
  include:
    - compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - sudo add-apt-repository main
  - sudo add-apt-repository universe
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcre2-dev libuv1-dev libyajl-dev gcc-9 g++-9 valgrind
  - git clone https://github.com/transceptor-technology/libcleri.git
  - cd ./libcleri/Release/
  - make
  - sudo make install
  - cd ../../Release/

script:
  - make test
  - CFLAGS="-Werror -std=gnu11" make
