kind: ConfigMap
apiVersion: v1

metadata:
  name: ti-config
  namespace: default

data:
  service_account.json: |-
    {
        "type": "service_account",
        "project_id": "EXAMPLE PROJECT ID",
        "private_key_id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "private_key": "-----BEGIN PRIVATE KEY-----\n....\n-----END PRIVATE KEY-----\n",
        "client_email": "thingsdb-sa@dexample-project.iam.gserviceaccount.com",
        "client_id": "012345678901234567890",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/thingsdb-sa%40example-project.iam.gserviceaccount.com"
      }


