apiVersion: v1
kind: Service
metadata:
  labels:
    app: thingsdb
  name: thingsdb
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: status
    port: 8080
  - name: client
    port: 9200
  - name: http
    port: 9210
  - name: node
    port: 9220
  selector:
    app: thingsdb
